name: Alô mundo

#Define o evento que dispara o workflow
on:
  workflow_dispatch:


#Define os jobs que serão executados
jobs:
  #Define o job chamado "alo"
  alo:
    #Define o sistema operacional que será usado
    runs-on: ubuntu-latest

    #Define as etapas do job
    steps:
      #Define a primeira etapa chamada "Checkout"
      - name: Ecoar alo mundo
        run: echo "Alo mundo!"
